<#
.SYNOPSIS
  Builds the FACET Android APK on a Windows box without Developer Mode.

.DESCRIPTION
  `tauri android build` does three things: build the frontend, cargo-build the
  Rust for each Android ABI, then hand off to Gradle. Between the second and
  third it drops a *symbolic link* to the built .so into app/src/main/jniLibs.

  Creating a symlink on Windows needs SeCreateSymbolicLinkPrivilege, which an
  ordinary account only has when Developer Mode is on. Without it the CLI dies
  at that step with "Creation symbolic link is not allowed for this system" —
  after a completely successful compile, which is what makes it so annoying.

  This script does the same three steps but copies the .so instead of linking
  it, then calls Gradle directly with the CLI's own Rust task skipped (that task
  just shells back into the CLI and would hit the same wall).

  Turning Developer Mode on in Settings > System > For developers makes this
  script unnecessary — plain `npx tauri android build --debug --apk` then works.
  It is kept because it also works on a locked-down machine.

.PARAMETER Release
  Build the release variant.

  It is signed if a signing key is configured, and unsigned if not -- the build
  never fails for want of one. Gradle looks for a keystore.properties at
  $env:FACET_SIGNING, or at ~/.facet-signing/keystore.properties; see the
  comment at the top of src-tauri/gen/android/app/build.gradle.kts. Neither the
  keystore nor its password is in this repository, and neither should ever be
  put here.

  An unsigned APK cannot be installed by adb or by a phone. Android has no
  concept of an unsigned app; the signature is the identity.
#>
param(
    [switch]$Release,
    [string]$Abi = 'aarch64'
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
if (-not $env:ANDROID_HOME) { $env:ANDROID_HOME = "$env:LOCALAPPDATA\Android\Sdk" }
if (-not $env:NDK_HOME) {
    # Newest NDK under the SDK, unless the caller already chose one.
    $ndkRoot = Join-Path $env:ANDROID_HOME 'ndk'
    $ndk = Get-ChildItem -Path $ndkRoot -Directory -ErrorAction SilentlyContinue |
        Sort-Object { [version]($_.Name -replace '[^0-9.].*$', '') } -Descending |
        Select-Object -First 1
    if ($ndk) { $env:NDK_HOME = $ndk.FullName }
}
# JAVA_HOME is left alone: if it is unset, gradlew falls back to whatever
# `java` is on PATH. Set it yourself if you need a specific JDK (17 works).
# Vite has been known to blow past the default heap on a cold build of this repo.
$env:NODE_OPTIONS = '--max-old-space-size=1536'

# Every Rust panic records the source file it came from, and unless told
# otherwise the compiler writes that as an absolute path on the machine doing
# the build. Those strings survive `strip` -- they are ordinary data, not
# symbols -- so a shipped .so spells out the builder's account name and the
# layout of their disk to anyone who runs `strings` on it. Cargo's `trim-paths`
# profile key does the same job but is not stable yet (checked on 1.96), so the
# remap goes through RUSTFLAGS, computed here rather than written down: the
# whole point is that no real path ends up in a file anyone reads.
$cargoHome = if ($env:CARGO_HOME) { $env:CARGO_HOME } else { Join-Path $env:USERPROFILE '.cargo' }
$remap = "--remap-path-prefix=$cargoHome=/cargo",
         "--remap-path-prefix=$root=/facet"
$env:RUSTFLAGS = ((@($env:RUSTFLAGS) + $remap) -ne '' -join ' ').Trim()

# ...and again through cargo's own config, because the environment variable on
# its own does not survive the trip. The tauri CLI spawns cargo itself, and
# whatever it does to the child environment, RUSTFLAGS set here does not reach
# it: a build run with these flags left every dependency fingerprint unchanged,
# so cargo happily reused .rlibs compiled without them. The give-away is that
# the leaked strings come from *dependencies* -- tao, tokio, tauri -- and only
# libfacet_lib.rlib ever got rebuilt.
#
# A config file next to the manifest is read by cargo directly, whoever
# launched it. It is written at build time rather than committed because its
# whole content is the absolute path this exercise exists to keep out of
# published files; .gitignore covers it.
$cargoCfgDir = Join-Path $root 'src-tauri\.cargo'
$cargoCfg = Join-Path $cargoCfgDir 'config.toml'
if (-not (Test-Path $cargoCfgDir)) { New-Item -ItemType Directory -Path $cargoCfgDir | Out-Null }
# .Replace, not -replace: the latter takes a regex, and a lone backslash is not
# a valid one. TOML basic strings need each backslash doubled.
$flagList = ($remap | ForEach-Object { '"' + $_.Replace('\', '\\') + '"' }) -join ', '
@"
# Generated by scripts/build-apk.ps1 on every build. Do not commit: the paths
# below are this machine's, which is the point -- they are what gets remapped
# out of the shipped binary. See the note in that script.
[build]
rustflags = [$flagList]
"@ | Out-File -FilePath $cargoCfg -Encoding utf8

Write-Host "   build paths remapped out of the binary" -ForegroundColor DarkGray

$profile = if ($Release) { 'release' } else { 'debug' }
$variant = if ($Release) { 'Release' } else { 'Debug' }

$apkRoot = Join-Path $root 'src-tauri\gen\android\app\build\outputs\apk'

function Get-Apk {
    if (-not (Test-Path $apkRoot)) { return $null }
    # Only APKs of the build type being asked for. The outputs tree is
    # <flavor>\<buildType>\, and both build types and several flavors live
    # there at once -- on this machine a 164 MB arm64 *debug* APK once sat
    # newer than every release one, and "newest .apk anywhere" would have
    # printed that as the result of a -Release build. The flavor is
    # deliberately not pinned: the CLI writes to `universal` when it is given
    # a single --target and to `<abi>` when gradle is driven directly, and
    # both are the same one-ABI APK.
    Get-ChildItem -Path $apkRoot -Filter '*.apk' -Recurse |
        Where-Object { $_.Directory.Name -eq $profile } |
        Sort-Object LastWriteTime -Descending | Select-Object -First 1
}

# Who signed the APK, straight out of the file.
#
# Printed on every build because "release APK" and "installable APK" are not
# the same thing and look identical in the outputs folder. An unsigned one
# fails at `adb install` with INSTALL_PARSE_FAILED_NO_CERTIFICATES, which is a
# long way from the build that produced it.
function Show-Signing($apk) {
    $sdk = if ($env:ANDROID_HOME) { $env:ANDROID_HOME } else { "$env:LOCALAPPDATA\Android\Sdk" }
    $signer = Get-ChildItem -Path (Join-Path $sdk 'build-tools') -Directory -ErrorAction SilentlyContinue |
        Sort-Object Name -Descending |
        ForEach-Object { Join-Path $_.FullName 'apksigner.bat' } |
        Where-Object { Test-Path $_ } | Select-Object -First 1
    if (-not $signer) {
        Write-Host "signing: unknown (no apksigner in the SDK build-tools)" -ForegroundColor DarkYellow
        return
    }
    $out = & $signer verify --print-certs $apk.FullName 2>&1 | Out-String
    if ($LASTEXITCODE -ne 0) {
        Write-Host "signing: UNSIGNED - this APK cannot be installed" -ForegroundColor Red
        Write-Host "  set up ~/.facet-signing/keystore.properties and rebuild" -ForegroundColor Red
        $global:LASTEXITCODE = 0
        return
    }
    $subject = ($out -split "`n" | Where-Object { $_ -match 'Signer #1 certificate DN' } | Select-Object -First 1)
    $sha = ($out -split "`n" | Where-Object { $_ -match 'Signer #1 certificate SHA-256 digest' } | Select-Object -First 1)
    Write-Host "signing: signed" -ForegroundColor Green
    if ($subject) { Write-Host ("  " + $subject.Trim()) -ForegroundColor DarkGray }
    # The fingerprint is the thing to check against a previous release: a
    # different one means a different key, which means no phone with the old
    # build on it can take the update.
    if ($sha) { Write-Host ("  " + $sha.Trim()) -ForegroundColor DarkGray }
}

function Show-Apk($apk) {
    Write-Host ""
    Write-Host "APK: $($apk.FullName)" -ForegroundColor Green
    # The timestamp is printed rather than checked: gradle skips packaging when
    # nothing changed, so an unchanged rebuild legitimately leaves the old mtime.
    # Treating "not newer than the run" as failure fails a perfectly good build.
    Write-Host ("size: {0:N1} MB   built: {1:yyyy-MM-dd HH:mm}" -f ($apk.Length / 1MB), $apk.LastWriteTime) -ForegroundColor Green
    Show-Signing $apk
}

$abiMap = @{
    'aarch64' = @{ Triple = 'aarch64-linux-android'; JniDir = 'arm64-v8a'; Flavor = 'Arm64' }
    'armv7'   = @{ Triple = 'armv7-linux-androideabi'; JniDir = 'armeabi-v7a'; Flavor = 'Arm' }
    'x86_64'  = @{ Triple = 'x86_64-linux-android'; JniDir = 'x86_64'; Flavor = 'X86_64' }
    'i686'    = @{ Triple = 'i686-linux-android'; JniDir = 'x86'; Flavor = 'X86' }
}
if (-not $abiMap.ContainsKey($Abi)) { throw "Unknown ABI '$Abi'. Use one of: $($abiMap.Keys -join ', ')" }
$target = $abiMap[$Abi]

# The frontend does not travel as files in the APK. `frontendDist` is compiled
# into libfacet_lib.so by tauri-build and compressed on the way in, which is
# why unzipping the APK finds no .js at all and why grepping the .so for a
# class name finds nothing either -- there is nothing to find in plaintext.
#
# The consequence is the one that matters: a change to dist/ is only in the
# build if cargo relinked the crate that embeds it. When cargo decides the
# crate is unchanged it keeps yesterday's .so, gradle repackages it happily,
# and the build is "successful" with none of the UI work in it. Touching
# build.rs when dist is the newer of the two costs a relink and removes the
# entire failure mode.
$soPath  = Join-Path $root (Join-Path 'src-tauri/target' (Join-Path $target.Triple (Join-Path $profile 'libfacet_lib.so')))
$distIdx = Join-Path $root 'dist/index.html'
if ((Test-Path $distIdx) -and (Test-Path $soPath)) {
    if ((Get-Item $distIdx).LastWriteTime -gt (Get-Item $soPath).LastWriteTime) {
        (Get-Item (Join-Path $root 'src-tauri/build.rs')).LastWriteTime = Get-Date
        Write-Host "   dist is newer than the last .so - forcing the embed to rebuild" -ForegroundColor DarkGray
    }
}

Write-Host "== 1/3  frontend + cargo ($($target.Triple), $profile)" -ForegroundColor Cyan
# Whether the CLI got all the way through on its own. Set inside the try below
# and read by the skip check further down; see the note there for why the
# symlink on disk cannot answer that question.
$cliOk = $false
$apkFirst = Get-Apk
$apkBefore = if ($apkFirst) { $apkFirst.LastWriteTime } else { $null }
Push-Location $root
try {
    # Expected to fail at the symlink step; everything before it is the work we
    # want, and a failure earlier shows up as the missing .so checked below.
    #
    # Deliberately NOT piped or 2>&1-redirected: Windows PowerShell wraps a
    # native command's stderr in ErrorRecords, and with $ErrorActionPreference
    # set to Stop the CLI's ordinary progress chatter would abort this script
    # before it ever got to the part that works around the failure.
    $cliArgs = @('tauri', 'android', 'build', '--apk', '--target', $Abi)
    if (-not $Release) { $cliArgs += '--debug' }
    & npx @cliArgs
    $cliOk = ($LASTEXITCODE -eq 0)
} catch {
    Write-Host "  (tauri CLI exited non-zero - continuing to the workaround)" -ForegroundColor DarkYellow
} finally {
    $global:LASTEXITCODE = 0
    Pop-Location
}

$jni = Join-Path $root "src-tauri\gen\android\app\src\main\jniLibs\$($target.JniDir)"
$jniSo = Join-Path $jni 'libfacet_lib.so'

# With Developer Mode on, the CLI gets past the symlink step and builds the APK
# itself — and then the workaround below is not merely unnecessary, it fails:
# step 2 tries to overwrite the very symlink the CLI just created and takes an
# IOException on a file the toolchain still holds, turning a perfectly good
# APK into a red build log.
#
# Two signals, and both are needed. The symlink says the CLI cleared the step
# this script exists to work around -- but it is a file on disk, so it is just
# as true the morning after a successful build as it is one second after one,
# and on its own it says nothing about the run that just happened. A run where
# the CLI failed early, on a tree where yesterday's symlink was still sitting
# there, took this branch, printed the APK yesterday left behind, and exited 0.
# Every source change in between was silently absent from the "successful"
# build, which is a worse outcome than any build failure.
#
# So: the exit code says whether *this* run's CLI finished, and the symlink
# says whether it finished by the path that also runs gradle. The APK's
# timestamp still cannot be a third check -- gradle legitimately skips
# packaging when nothing changed -- but it is worth printing when it predates
# the run, because that is either a no-op rebuild or the bug above coming back.
$link = Get-Item -LiteralPath $jniSo -Force -ErrorAction SilentlyContinue
if ($cliOk -and $link -and ($link.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
    $apk = Get-Apk
    if ($apk) {
        Write-Host "the CLI symlinked and built on its own - skipping the workaround" -ForegroundColor DarkYellow
        Show-Apk $apk
        if ($apkBefore -and $apk.LastWriteTime -le $apkBefore) {
            Write-Host "  note: gradle did not repackage - nothing changed since the last build" -ForegroundColor DarkYellow
        }
        exit 0
    }
}

$so = Join-Path $root "src-tauri\target\$($target.Triple)\$profile\libfacet_lib.so"
if (-not (Test-Path $so)) {
    throw "cargo did not produce $so - the failure above was real, not the symlink step."
}

Write-Host "== 2/3  copying the shared library into jniLibs" -ForegroundColor Cyan
if (-not (Test-Path $jni)) { New-Item -ItemType Directory -Force -Path $jni | Out-Null }

# A symlink left by an earlier run that *did* get past the CLI's symlink step
# has to go before the copy, and not because it is merely in the way: it points
# at $so, so `Copy-Item $so $jniSo -Force` follows it and copies the file onto
# itself. Windows reports that as "being used by another process", which reads
# like a stray lock and sent this script's author looking for a gradle daemon
# to stop. Stopping the daemon does not help; the source and destination are
# one file.
#
# It goes to the Recycle Bin rather than being deleted outright, per this
# machine's standing rule. It is a link, so what is recycled is four hundred
# bytes of reparse point, not the .so it names -- and the .so is the thing on
# the very next line, still where cargo left it.
$stale = Get-Item -LiteralPath $jniSo -Force -ErrorAction SilentlyContinue
if ($stale -and ($stale.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
    Add-Type -AssemblyName Microsoft.VisualBasic
    [Microsoft.VisualBasic.FileIO.FileSystem]::DeleteFile(
        $jniSo, 'OnlyErrorDialogs', 'SendToRecycleBin')
    Write-Host "  cleared the symlink a previous run left here" -ForegroundColor DarkGray
}
# The library is what carries the UI, so it has to be newer than the UI. If it
# is not, cargo did not relink -- either it decided the crate was untouched, or
# the CLI died before it got that far -- and every step from here on would go
# through the motions on a library built from an older dist, ending in a green
# "APK:" line for a build with none of the current work in it. That is the
# failure this script has produced twice, and it is silent both times, so it
# stops the build rather than warning.
if ((Test-Path $distIdx) -and ((Get-Item $distIdx).LastWriteTime -gt (Get-Item $so).LastWriteTime)) {
    Write-Host ""
    Write-Host "STALE: libfacet_lib.so predates dist - cargo did not relink." -ForegroundColor Red
    Write-Host ("  dist/index.html  {0}" -f (Get-Item $distIdx).LastWriteTime) -ForegroundColor Red
    Write-Host ("  libfacet_lib.so  {0}" -f (Get-Item $so).LastWriteTime) -ForegroundColor Red
    Write-Host "  the frontend is compiled into that library, so packaging now would ship the old UI." -ForegroundColor Red
    exit 1
}

Copy-Item $so $jniSo -Force

Write-Host "== 3/3  gradle assemble$($target.Flavor)$variant" -ForegroundColor Cyan
Push-Location (Join-Path $root 'src-tauri\gen\android')
try {
    & .\gradlew.bat "assemble$($target.Flavor)$variant" "-xrustBuild$($target.Flavor)$variant"
    if ($LASTEXITCODE -ne 0) { throw "gradle failed with exit code $LASTEXITCODE" }
} finally {
    Pop-Location
}

$apk = Get-Apk
if (-not $apk) { throw "gradle reported success but there is no APK under $apkRoot." }
Show-Apk $apk
