/**
 * Audio editor harness — item 5.
 *
 * Same bargain as the video one: Rust is already checked against real encodes,
 * so what is checked here is everything between a click and an `AudioJob` —
 * the span arithmetic, the readouts, the promise the export button makes, and
 * the wiring that connects a control to the thing it claims to control.
 *
 * The host is a stub and the *audio is real*: a genuine 8-second file off
 * `devfixtures/`, played by a genuine `<audio>` element, because `currentTime` is
 * the input half of this module reads and faking it would be testing the fake.
 *
 * Driven through the DOM — controls are found by the tooltip a person would
 * hover — so a method that works but is wired to nothing still fails.
 */

import "../styles/base.css";
import "../styles/aedit.css";
import { themes } from "@core/theme/theme-engine";
import { AudioEditor, type AudioJob } from "@ui/aedit";
import type { Media } from "@ui/vedit";

// Without this every `--fct-*` token is undefined and the harness renders
// black on black, which hides exactly the layout problems a screenshot of it
// is here to catch.
themes.init();

let passed = 0;
let failed = 0;

function ok(what: string, cond: boolean, saw = ""): void {
  if (cond) {
    passed++;
  } else {
    failed++;
    console.error(`FAIL  ${what}${saw ? `  — saw ${saw}` : ""}`);
  }
}

const near = (a: number, b: number, eps = 0.06): boolean => Math.abs(a - b) < eps;

/** Eight seconds of 440 Hz, mono, 22.05 kHz. Generated by ffmpeg. */
const MEDIA: Media = {
  duration: 8,
  bitrate: 32000,
  format: "mp3",
  width: 0,
  height: 0,
  tracks: [
    { index: 0, kind: "audio", codec: "mp3", width: 0, height: 0, fps: 0,
      channels: 1, sampleRate: 22050, rotation: 0, language: "" },
  ],
};

let lastJob: AudioJob | null = null;
let doneCb: ((d: unknown) => void) | null = null;
let progressCb: ((p: unknown) => void) | null = null;
let refreshed = 0;
let peaksAsked: { path: string; buckets: number } | null = null;

const editor = new AudioEditor({
  fileUrl: (p) => Promise.resolve(p),
  probe: () => Promise.resolve(MEDIA),
  peaks: (path, buckets) => {
    peaksAsked = { path, buckets };
    // A ramp rather than a constant: a draw that ignores its input still looks
    // like a waveform when every bucket is the same number.
    return Promise.resolve(Array.from({ length: buckets }, (_, i) => i / buckets));
  },
  runAudioJob: (job) => {
    lastJob = job;
    return Promise.resolve(7);
  },
  cancelJob: () => Promise.resolve(),
  onProgress: (cb) => {
    progressCb = cb as (p: unknown) => void;
    return () => {};
  },
  onDone: (cb) => {
    doneCb = cb as (d: unknown) => void;
    return () => {};
  },
  refresh: () => {
    refreshed++;
  },
});

// ── Reaching into the DOM the way a person would ─────────────────────────────

const root = (): HTMLElement => document.querySelector<HTMLElement>(".aedit")!;
const audio = (): HTMLAudioElement => root().querySelector("audio")!;
const note = (): string => root().querySelector(".aedit-note")?.textContent ?? "";
const clock = (): string => root().querySelector(".aedit-clock")?.textContent ?? "";

function press(fragment: string): void {
  const b = Array.from(root().querySelectorAll<HTMLButtonElement>("button")).find((x) =>
    x.title.toLowerCase().includes(fragment.toLowerCase()),
  );
  if (!b) throw new Error(`no button whose tooltip mentions "${fragment}"`);
  b.click();
}

function toggleCheck(label: string): void {
  const l = Array.from(root().querySelectorAll<HTMLLabelElement>(".aedit-check")).find((x) =>
    x.textContent?.includes(label),
  );
  const i = l?.querySelector("input");
  if (!i) throw new Error(`no checkbox called "${label}"`);
  i.checked = !i.checked;
  i.dispatchEvent(new Event("change"));
}

function selectFor(label: string): HTMLSelectElement {
  const l = Array.from(root().querySelectorAll<HTMLLabelElement>(".aedit-check")).find(
    (x) => x.textContent?.startsWith(label),
  );
  const s = l?.querySelector("select");
  if (!s) throw new Error(`no dropdown called "${label}"`);
  return s;
}

function choose(label: string, value: string): void {
  const s = selectFor(label);
  s.value = value;
  s.dispatchEvent(new Event("change"));
}

const readouts = (): string[] =>
  Array.from(root().querySelectorAll<HTMLElement>(".aedit-read")).map((x) => x.textContent ?? "");

/** The sentence under the noise picker, which is where its one caveat lives. */
const hint = (): string =>
  root().querySelector<HTMLElement>(".aedit-hint")?.textContent ?? "";

const exportLabel = (): string =>
  Array.from(root().querySelectorAll("button")).find((b) => b.textContent?.startsWith("Export"))
    ?.textContent ?? "";

function seek(t: number): Promise<void> {
  const a = audio();
  return new Promise((res) => {
    a.addEventListener("seeked", () => res(), { once: true });
    a.currentTime = t;
    // A seek to where the head already is fires nothing.
    setTimeout(res, 250);
  });
}

/**
 * Press export, catch the job, then tell the editor it finished — the editor
 * refuses a second export while one is in flight, which is right, and which
 * means a harness that never finishes one gets a single assertion out of it.
 */
async function exportNow(): Promise<AudioJob> {
  lastJob = null;
  press("never touched");
  for (let i = 0; i < 60 && !lastJob; i++) await new Promise((r) => setTimeout(r, 16));
  // Asserted, not narrowed: `lastJob` is only written inside the host callback,
  // which the checker cannot see, so it still believes the `= null` above is the
  // whole story and calls everything past the guard `never`.
  const job = lastJob as AudioJob | null;
  if (!job) throw new Error("export never produced a job");
  // The id only arrives when the promise resolves, so a "done" fired right now
  // has nothing to match against and is correctly ignored.
  await new Promise((r) => setTimeout(r, 0));
  doneCb?.({ id: 7, ok: true, output: job.output, leftover: "", error: "", copied: false });
  refreshed = 0;
  return job;
}

// ── The run ──────────────────────────────────────────────────────────────────

async function run(): Promise<void> {
  // First, because it only fails first: the panel sets `hidden`, but a `display`
  // rule in the stylesheet outranks that, and the video editor shipped once with
  // an empty panel pinned over the file list for exactly that reason. Every
  // assertion below passed while that was true.
  ok("the editor stays out of the way until a file is opened",
    getComputedStyle(root()).display === "none", getComputedStyle(root()).display);

  await editor.open("C:/recordings/aeditcheck.mp3");
  // Served off the project root by the dev server, not out of `public/` — that
  // folder is copied wholesale into the shipped app, and a test tone has no
  // business inside a release build.
  audio().src = "/devfixtures/aeditcheck.mp3";
  await new Promise<void>((res) => {
    if (audio().readyState >= 1) return res();
    audio().addEventListener("loadedmetadata", () => res(), { once: true });
    setTimeout(res, 3000);
  });

  ok("real audio actually loaded, or nothing below means anything",
    near(audio().duration, 8, 0.2), String(audio().duration));
  ok("the file is described rather than merely opened",
    note().includes("0:08") && note().includes("mono"), note());

  // ── The waveform ──────────────────────────────────────────────────────────

  for (let i = 0; i < 100 && !peaksAsked; i++) await new Promise((r) => setTimeout(r, 20));
  ok("the shape is scanned in Rust, for the file that was opened",
    peaksAsked?.path === "C:/recordings/aeditcheck.mp3", peaksAsked?.path ?? "never asked");
  ok("at a resolution finer than the screen", (peaksAsked?.buckets ?? 0) >= 1000,
    String(peaksAsked?.buckets));
  const canvas = root().querySelector<HTMLCanvasElement>(".aedit-wave")!;
  ok("and drawn onto a canvas with real pixels in it", canvas.width > 100 && canvas.height > 20,
    `${canvas.width}x${canvas.height}`);

  // ── The span model ────────────────────────────────────────────────────────

  let job = await exportNow();
  ok("opening a file keeps all of it",
    job.spans?.length === 1 && near(job.spans[0]!.start, 0) && near(job.spans[0]!.end, 8),
    JSON.stringify(job.spans));

  await seek(2);
  press("Split here");
  job = await exportNow();
  ok("a split on its own removes nothing — two adjacent spans are the whole file",
    job.spans?.length === 2 && near(job.spans[0]!.end, 2, 0.2) && near(job.spans[1]!.end, 8, 0.2),
    JSON.stringify(job.spans));

  await seek(1);
  press("Remove this piece");
  job = await exportNow();
  ok("removing takes the piece under the playhead, not the first one",
    job.spans?.length === 1 && near(job.spans[0]!.start, 2, 0.2), JSON.stringify(job.spans));

  press("Undo");
  job = await exportNow();
  ok("undo brings the removed piece back", job.spans?.length === 2, JSON.stringify(job.spans));
  press("Redo");
  job = await exportNow();
  ok("redo takes it away again", job.spans?.length === 1, JSON.stringify(job.spans));

  press("Keep all of it");
  await seek(3);
  press("Start here");
  await seek(6);
  press("End here");
  job = await exportNow();
  ok("trimming both ends leaves one span between them",
    job.spans?.length === 1 && near(job.spans[0]!.start, 3, 0.2) && near(job.spans[0]!.end, 6, 0.2),
    JSON.stringify(job.spans));
  ok("and the clock says how long what is left will be", clock().includes("0:03"), clock());

  // ── Preview follows the model ─────────────────────────────────────────────

  press("Keep all of it");
  await seek(2);
  press("Split here");
  await seek(1);
  press("Remove this piece");
  await seek(0.5);
  await new Promise((r) => setTimeout(r, 400));
  ok("the playhead refuses to sit inside a piece that was cut out",
    audio().currentTime >= 2, String(audio().currentTime));
  press("Keep all of it");

  // ── Clicking the waveform is how you get anywhere ─────────────────────────

  const box = root().querySelector<HTMLElement>(".aedit-stage")!.getBoundingClientRect();
  root().querySelector(".aedit-stage")!.dispatchEvent(
    new PointerEvent("pointerdown", {
      clientX: box.left + box.width * 0.5,
      clientY: box.top + box.height / 2,
      bubbles: true,
      pointerId: 1,
    }),
  );
  ok("clicking halfway along the waveform lands halfway through the file",
    near(audio().currentTime, 4, 0.3), String(audio().currentTime));
  ok("and the playhead moves with it",
    near(parseFloat(root().querySelector<HTMLElement>(".aedit-head")!.style.left), 50, 3),
    root().querySelector<HTMLElement>(".aedit-head")!.style.left);

  // ── Level ─────────────────────────────────────────────────────────────────

  press("Quieter");
  press("Quieter");
  press("Quieter");
  press("Quieter");
  press("Quieter");
  press("Quieter");
  ok("the gain readout is in dB and signed", readouts().includes("-6 dB"),
    JSON.stringify(readouts()));
  ok("and the preview is actually quieter, so it can be judged before the encode",
    near(audio().volume, 0.501, 0.01), String(audio().volume));
  job = await exportNow();
  ok("the job carries the gain", job.gainDb === -6, String(job.gainDb));

  for (let i = 0; i < 40; i++) press("Louder");
  ok("gain stops at a sane ceiling rather than running away",
    readouts().includes("+24 dB"), JSON.stringify(readouts()));
  ok("and says that the preview cannot follow a boost, instead of quietly lying",
    note().toLowerCase().includes("cannot play louder"), note());
  for (let i = 0; i < 24; i++) press("Quieter");

  toggleCheck("Normalise");
  job = await exportNow();
  ok("normalise reaches the job", job.normalize === true, String(job.normalize));
  toggleCheck("Normalise");

  // ── Time ──────────────────────────────────────────────────────────────────

  // Three rungs to reach 2×, not two: the audio ladder has 1.25 in it, which the
  // video one does not. Podcast speeds are the whole reason this control exists
  // and 1.25 is the one people actually pick.
  press("Faster");
  press("Faster");
  press("Faster");
  job = await exportNow();
  ok("the speed stepper walks the rungs", job.speed === 2, String(job.speed));
  ok("playback follows it, so the speed is auditioned rather than guessed",
    near(audio().playbackRate, 2, 0.01), String(audio().playbackRate));
  ok("and the clock halves the output length", clock().includes("0:04"), clock());
  press("Slower");
  press("Slower");
  press("Slower");

  toggleCheck("Fade");
  job = await exportNow();
  ok("one Fade checkbox asks for both ends", job.fadeIn === 1 && job.fadeOut === 1,
    `${job.fadeIn}/${job.fadeOut}`);
  toggleCheck("Fade");

  toggleCheck("Mono");
  job = await exportNow();
  ok("mono reaches the job", job.mono === true, String(job.mono));
  toggleCheck("Mono");

  // ── Noise (item 18) ───────────────────────────────────────────────────────
  //
  // The measuring of what each preset does to a recording is done in Rust,
  // against real encodes. What is checked here is the other half: that the rung
  // you picked is the rung that gets sent, that the ladder is offered in the
  // order it gets stronger, and that the one preset with a real cost says so on
  // the control rather than in a comment nobody sees.

  ok("the noise ladder is offered weakest first",
    Array.from(selectFor("Remove noise").options).map((o) => o.value).join(",")
      === ",room,traffic,voice,strong",
    Array.from(selectFor("Remove noise").options).map((o) => o.value).join(","));

  job = await exportNow();
  ok("a file nobody asked to clean carries no preset", job.denoise === "", String(job.denoise));

  choose("Remove noise", "voice");
  ok("picking a preset says what it is for",
    hint().includes("speech"), hint());
  job = await exportNow();
  ok("the chosen preset reaches the job", job.denoise === "voice", String(job.denoise));

  choose("Remove noise", "strong");
  ok("the one preset that can hurt the voice warns about it",
    /quiet as the noise|takes a lot of the talker/i.test(hint()), hint());

  ok("cleaning a recording gives up the no-re-encode path",
    !exportLabel().includes("no re-encode"), exportLabel());
  choose("Remove noise", "");
  ok("and gets it back when you turn it off",
    exportLabel().includes("no re-encode"), exportLabel());

  // ── Output ────────────────────────────────────────────────────────────────

  ok("a plain trim advertises that it will not re-encode",
    exportLabel().includes("no re-encode"), exportLabel());
  toggleCheck("Normalise");
  ok("and stops the moment the samples have to be touched",
    !exportLabel().includes("no re-encode"), exportLabel());
  toggleCheck("Normalise");
  choose("Format", "flac");
  ok("changing the container gives up the free path too — a copy into a new one is not a copy",
    !exportLabel().includes("no re-encode"), exportLabel());
  ok("the bitrate control switches off for a format that has no bitrate",
    selectFor("Bitrate").disabled, String(selectFor("Bitrate").disabled));
  job = await exportNow();
  ok("and the output name follows the format", job.output.endsWith(".flac"), job.output);

  choose("Format", "mp3");
  ok("switching back re-enables it", !selectFor("Bitrate").disabled);
  choose("Bitrate", "320");
  job = await exportNow();
  ok("the chosen bitrate reaches the job", job.bitrate === 320, String(job.bitrate));
  ok("the export never lands on the file it came from",
    job.output.endsWith("aeditcheck-edit.mp3") && !job.output.endsWith("/aeditcheck.mp3"),
    job.output);
  ok("and it goes next to the original rather than somewhere else",
    job.output.startsWith("C:/recordings/"), job.output);
  ok("the source is sent untouched, as an input", job.inputs[0] === "C:/recordings/aeditcheck.mp3",
    JSON.stringify(job.inputs));

  // ── Progress and failure ──────────────────────────────────────────────────

  // Start one and deliberately leave it running — progress only means something
  // while there is something to be in the middle of.
  lastJob = null;
  refreshed = 0;
  press("never touched");
  for (let i = 0; i < 60 && !lastJob; i++) await new Promise((r) => setTimeout(r, 16));
  await new Promise((r) => setTimeout(r, 0));

  progressCb?.({ id: 7, fraction: 0.42, seconds: 3, speed: 12.5, fps: 0 });
  ok("progress for this job is reported", note().includes("42%"), note());
  progressCb?.({ id: 99, fraction: 0.9, seconds: 9, speed: 1, fps: 0 });
  ok("progress for somebody else's job is not", note().includes("42%"), note());

  doneCb?.({ id: 7, ok: false, output: "", leftover: "C:/recordings/x.mp3.facet-part",
    error: "Invalid argument", copied: false });
  ok("a failure says what went wrong", note().includes("Invalid argument"), note());
  ok("and names the partial rather than pretending it is not there",
    note().includes(".facet-part"), note());
  ok("without claiming the folder changed", refreshed === 0, String(refreshed));

  // A failure ends the job, so the success case needs its own.
  lastJob = null;
  press("never touched");
  for (let i = 0; i < 60 && !lastJob; i++) await new Promise((r) => setTimeout(r, 16));
  await new Promise((r) => setTimeout(r, 0));
  doneCb?.({ id: 7, ok: true, output: "C:/recordings/aeditcheck-edit.mp3", leftover: "",
    error: "", copied: true });
  ok("a copy that re-encoded nothing says so", note().includes("original bytes"), note());
  ok("and the folder is told to reload so the file appears", refreshed === 1, String(refreshed));

  // ── Closing ───────────────────────────────────────────────────────────────

  editor.close();
  ok("closing puts the panel away", getComputedStyle(root()).display === "none",
    getComputedStyle(root()).display);
  ok("and stops the sound rather than leaving it playing behind the file list",
    audio().paused, String(audio().paused));

  console.log(`aedit: ${passed} passed${failed ? `, ${failed} FAILED` : ""}`);

  // Left open and loaded on purpose. This page is also how the editor gets
  // *looked at*, and both of the bugs the video editor shipped — a panel over
  // the file list, a postage-stamp picture in a full-size stage — were invisible
  // to every assertion above and obvious in a screenshot.
  await editor.open("C:/recordings/aeditcheck.mp3");
  audio().src = "/devfixtures/aeditcheck.mp3";
}

void run().catch((e: unknown) => {
  console.error(`aedit harness threw: ${String(e)}`);
});
