/**
 * Video editor harness — item 4.
 *
 * The Rust side is already checked against real encodes; what cannot be checked
 * there is everything between a click and a `Job`. That is where the bugs of
 * this shape live: a span list that looks right on screen and is off by one
 * boundary, a crop rectangle mapped through the element box instead of the
 * picture box, a "no re-encode" label that promises something the exporter will
 * not do.
 *
 * So the host here is a stub and the *video is real*: a genuine 8-second file
 * off `devfixtures/`, played by a genuine `<video>` element, because `currentTime`
 * and `videoWidth` are the inputs half of this module reads and faking them
 * would be testing the fake.
 *
 * Driven through the DOM — the buttons are found by their tooltips and
 * `.click()`ed — so the wiring is under test alongside the logic. A method
 * called directly proves the method works and nothing about whether anything
 * calls it.
 */

import "../styles/base.css";
import "../styles/vedit.css";
import { themes } from "@core/theme/theme-engine";
import { suggestName, VideoEditor, type Job, type Media } from "@ui/vedit";

// Fetched, not imported: see the note in facecheck.ts. `scripts/fixtures.ps1`
// stages it; without it this one image 404s and the rest of the harness runs.
const faceAUrl = "/_autoblurcheck/face-a.jpg";

// Without this every `--fct-*` token is undefined, and the harness renders a
// black-on-black screenshot that hides exactly the layout problems a screenshot
// is here to catch. Found by looking at one.
themes.init();

let passed = 0;
let failed = 0;

function ok(what: string, cond: boolean, saw = ""): void {
  if (cond) {
    passed++;
  } else {
    failed++;
    console.error(`FAIL  ${what}${saw ? `  — saw ${saw}` : ""}`);
  }
}

const near = (a: number, b: number, eps = 0.06): boolean => Math.abs(a - b) < eps;

/** A 320×180 clip, eight seconds, 25 fps. Generated by ffmpeg, checked nowhere. */
const MEDIA: Media = {
  duration: 8,
  bitrate: 100000,
  format: "mov,mp4",
  width: 320,
  height: 180,
  tracks: [
    { index: 0, kind: "video", codec: "h264", width: 320, height: 180, fps: 25,
      channels: 0, sampleRate: 0, rotation: 0, language: "" },
    { index: 1, kind: "audio", codec: "aac", width: 0, height: 0, fps: 0,
      channels: 1, sampleRate: 44100, rotation: 0, language: "" },
  ],
};

/** A 1×1 PNG. The filmstrip only needs bytes that decode. */
const PIXEL = Uint8Array.from(
  atob(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==",
  ),
  (c) => c.charCodeAt(0),
);

let lastJob: Job | null = null;
let doneCb: ((d: unknown) => void) | null = null;
let progressCb: ((p: unknown) => void) | null = null;
let refreshed = 0;

/**
 * A 320×180 frame with a real face in it, built once (item 19).
 *
 * The face has to be a photograph — the detector was trained on photographs and
 * finds nothing in a drawn oval — but a full 512² frame sixteen times over is
 * seconds of harness runtime for no extra coverage, so the portrait is scaled
 * into a frame the size of the clip. That is also what the real path does: the
 * extractor hands back a downscaled frame and the boxes are scaled back up.
 */
let faceFrame: Uint8Array | null = null;
let serveFaces = false;

async function buildFaceFrame(): Promise<void> {
  const img = new Image();
  img.src = faceAUrl;
  await img.decode();
  const c = document.createElement("canvas");
  c.width = 320;
  c.height = 180;
  const g = c.getContext("2d")!;
  g.fillStyle = "#202020";
  g.fillRect(0, 0, 320, 180);
  // Scaled to 260 and hung off the top so the face sits inside the frame at
  // about 52 px across. Smaller than this and the cascade stops agreeing with
  // itself three times over — which is a real limit of the detector at video
  // resolutions, not a quirk of the harness, and is why VIDEO_WIDTH is 640
  // rather than something smaller.
  g.drawImage(img, 60, -40, 260, 260);
  const blob = await new Promise<Blob | null>((r) => c.toBlob(r, "image/png"));
  if (blob) faceFrame = new Uint8Array(await blob.arrayBuffer());
}

const editor = new VideoEditor({
  fileUrl: (p) => Promise.resolve(p),
  probe: () => Promise.resolve(MEDIA),
  frameAt: () => Promise.resolve(serveFaces && faceFrame ? faceFrame : PIXEL),
  runJob: (job) => {
    lastJob = job;
    return Promise.resolve(7);
  },
  cancelJob: () => Promise.resolve(),
  onProgress: (cb) => {
    progressCb = cb as (p: unknown) => void;
    return () => {};
  },
  onDone: (cb) => {
    doneCb = cb as (d: unknown) => void;
    return () => {};
  },
  refresh: () => {
    refreshed++;
  },
});

// ── Reaching into the DOM the way a person would ─────────────────────────────

const root = (): HTMLElement => document.querySelector<HTMLElement>(".vedit")!;
const video = (): HTMLVideoElement => root().querySelector("video")!;

/** Find a control by the tooltip a user would hover to find it. */
function press(fragment: string): void {
  const b = Array.from(root().querySelectorAll<HTMLButtonElement>("button")).find((x) =>
    x.title.toLowerCase().includes(fragment.toLowerCase()),
  );
  if (!b) throw new Error(`no button whose tooltip mentions "${fragment}"`);
  b.click();
}

function toggleCheck(label: string): void {
  const l = Array.from(root().querySelectorAll<HTMLLabelElement>(".vedit-check")).find((x) =>
    x.textContent?.includes(label),
  );
  const i = l?.querySelector("input");
  if (!i) throw new Error(`no checkbox called "${label}"`);
  i.checked = !i.checked;
  i.dispatchEvent(new Event("change"));
}

/** The span bars as fractions of the timeline, read off their inline styles. */
function bars(): { left: number; width: number }[] {
  return Array.from(root().querySelectorAll<HTMLElement>(".vedit-span")).map((b) => ({
    left: parseFloat(b.style.left),
    width: parseFloat(b.style.width),
  }));
}

function seek(t: number): Promise<void> {
  const v = video();
  return new Promise((res) => {
    v.addEventListener("seeked", () => res(), { once: true });
    v.currentTime = t;
    // A seek to where the head already is fires nothing.
    setTimeout(res, 250);
  });
}

/**
 * Press export, catch the job, then tell the editor it finished.
 *
 * The completion is not politeness: the editor refuses a second export while
 * one is in flight — which is right, and which means a harness that never
 * finishes a job gets exactly one assertion out of it.
 */
async function exportNow(): Promise<Job> {
  lastJob = null;
  press("never touched");
  for (let i = 0; i < 60 && !lastJob; i++) await new Promise((r) => setTimeout(r, 16));
  // Annotated, not narrowed: `lastJob` is only ever written from inside the host
  // callback, which the checker cannot see, so it still believes the `= null`
  // above is the whole story and calls everything past the guard `never`.
  const job = lastJob as Job | null;
  if (!job) throw new Error("export never produced a job");
  // `lastJob` is set synchronously inside the host callback, but the editor
  // only learns the id when the promise resolves — so a "done" fired right now
  // arrives before there is a job to match it against, and is correctly
  // ignored. Wait for the assignment before pretending the encode finished.
  await new Promise((r) => setTimeout(r, 0));
  doneCb?.({ id: 7, ok: true, output: job.output, leftover: "", error: "", copied: false });
  refreshed = 0;
  return job;
}

// ── The run ──────────────────────────────────────────────────────────────────

async function run(): Promise<void> {
  // Before anything else, because it only fails before anything else: the panel
  // sets `hidden`, but a `display` rule in the stylesheet outranks that, and the
  // shipped build opened with an empty editor pinned over the file list. Every
  // assertion below passed while that was true — it only showed up in a
  // screenshot of the real app.
  ok("the editor stays out of the way until a clip is opened",
    getComputedStyle(root()).display === "none", getComputedStyle(root()).display);

  await buildFaceFrame();
  ok("the harness has a real photograph to feed the detector", faceFrame !== null);

  await editor.open("C:/clips/veditcheck.mp4");
  // The stub hands back a path; point the element at the real file.
  // Served straight off the project root by the dev server. Deliberately not in
  // `public/`, which is copied wholesale into the shipped app — an 8-second test
  // clip has no business inside a release build.
  video().src = "/devfixtures/veditcheck.mp4";
  await new Promise<void>((res) => {
    if (video().readyState >= 1) return res();
    video().addEventListener("loadedmetadata", () => res(), { once: true });
    setTimeout(res, 3000);
  });

  ok("a real video actually loaded, or nothing below means anything",
    video().videoWidth === 320 && video().videoHeight === 180,
    `${video().videoWidth}x${video().videoHeight}`);

  // ── The span model ────────────────────────────────────────────────────────

  ok("opening a clip keeps all of it", bars().length === 1 && near(bars()[0]!.width, 100, 0.5),
    JSON.stringify(bars()));

  await seek(2);
  press("Split here");
  ok("splitting makes two pieces", bars().length === 2, JSON.stringify(bars()));
  ok("and the boundary lands where the playhead was",
    near(bars()[0]!.width, 25, 0.5) && near(bars()[1]!.left, 25, 0.5), JSON.stringify(bars()));

  let job = await exportNow();
  ok("a split on its own removes nothing — two adjacent spans are still the whole clip",
    job.spans?.length === 2 &&
      near(job.spans[0]!.start, 0) && near(job.spans[1]!.end, 8, 0.2),
    JSON.stringify(job.spans));

  await seek(1);
  press("Drop the piece");
  ok("dropping removes the piece under the playhead, not the first one",
    bars().length === 1 && near(bars()[0]!.left, 25, 0.5), JSON.stringify(bars()));

  job = await exportNow();
  ok("and the job asks for what survived", near(job.spans![0]!.start, 2), JSON.stringify(job.spans));

  press("Undo");
  ok("undo brings the dropped piece back", bars().length === 2, JSON.stringify(bars()));
  press("Redo");
  ok("redo takes it away again", bars().length === 1, JSON.stringify(bars()));

  press("Keep all of it");
  ok("reset restores the whole clip", bars().length === 1 && near(bars()[0]!.width, 100, 0.5),
    JSON.stringify(bars()));

  await seek(3);
  press("Trim the start");
  await seek(6);
  press("Trim the end");
  job = await exportNow();
  ok("trimming both ends leaves one span between them",
    job.spans?.length === 1 && near(job.spans[0]!.start, 3, 0.2) && near(job.spans[0]!.end, 6, 0.2),
    JSON.stringify(job.spans));

  // ── Preview follows the model ─────────────────────────────────────────────

  press("Keep all of it");
  await seek(2);
  press("Split here");
  await seek(1);
  press("Drop the piece");
  await seek(0.5);
  await new Promise((r) => setTimeout(r, 400));
  ok("the playhead refuses to sit inside a piece that was cut out",
    video().currentTime >= 2, String(video().currentTime));

  // ── The lossless promise ──────────────────────────────────────────────────

  press("Keep all of it");
  const label = (): string =>
    Array.from(root().querySelectorAll("button")).find((b) => b.textContent?.startsWith("Export"))
      ?.textContent ?? "";
  ok("a plain trim advertises that it will not re-encode", label().includes("no re-encode"), label());
  press("Turn a quarter clockwise");
  ok("and stops advertising it the moment the frame has to be touched",
    !label().includes("no re-encode"), label());
  press("Turn a quarter the other way");
  toggleCheck("Frame-exact");
  ok("asking for frame-exact also gives up the free path",
    !label().includes("no re-encode"), label());
  toggleCheck("Frame-exact");

  // ── Geometry ──────────────────────────────────────────────────────────────

  press("Turn a quarter clockwise");
  job = await exportNow();
  ok("a quarter turn is sent as 90", job.rotate === 90, String(job.rotate));
  ok("and the preview is turned to match", video().style.transform.includes("rotate(90deg)"),
    video().style.transform);
  ok("with its limits swapped so it does not overflow the stage",
    video().classList.contains("vedit-turned"));
  press("Turn a quarter the other way");
  ok("turning back leaves no transform", video().style.transform === "", video().style.transform);

  press("Mirror left to right");
  job = await exportNow();
  ok("a mirror is sent as flipH", job.flipH === true && job.flipV === false, JSON.stringify(job.flipH));
  press("Mirror left to right");

  // Three rungs above 1x, not two: the ladder gained a 1.25 between 1 and 1.5
  // so that the speeds people actually reach for are a press apart. This check
  // was written against the older, coarser ladder and asserted the destination
  // rather than the walk, so it started failing the moment the rungs got
  // finer -- with nothing wrong with the control. Stepping one at a time and
  // naming each rung says what is meant, and fails loudly if a rung moves.
  const speedNow = (): string =>
    root().querySelector(".vedit-speed")?.textContent ?? "";
  press("Faster");
  ok("one rung up from 1x is the fine one", speedNow() === "1.25×", speedNow());
  press("Faster");
  ok("and the next is 1.5", speedNow() === "1.5×", speedNow());
  press("Faster");
  job = await exportNow();
  ok("the speed stepper walks the rungs", job.speed === 2, String(job.speed));
  ok("and the clock says how long the output will be",
    (root().querySelector(".vedit-clock")?.textContent ?? "").includes("0:04"),
    root().querySelector(".vedit-clock")?.textContent ?? "");
  press("Slower");
  press("Slower");
  press("Slower");
  ok("and walks all the way back down", speedNow() === "1×", speedNow());

  // ── Crop, which is the one with real arithmetic in it ─────────────────────
  //
  // The stage is wider than the clip, so the picture is letterboxed inside the
  // element. Mapping through the element's own box instead of the picture's is
  // the classic bug and puts the rectangle somewhere else entirely.

  press("Crop");
  const el = video().getBoundingClientRect();
  const scale = Math.min(el.width / 320, el.height / 180);
  const pw = 320 * scale;
  const ph = 180 * scale;
  const px = el.left + (el.width - pw) / 2;
  const py = el.top + (el.height - ph) / 2;
  const stage = root().querySelector<HTMLElement>(".vedit-stage")!;
  const drag = (x0: number, y0: number, x1: number, y1: number): void => {
    for (const [type, x, y] of [
      ["pointerdown", x0, y0],
      ["pointermove", x1, y1],
      ["pointerup", x1, y1],
    ] as [string, number, number][]) {
      stage.dispatchEvent(
        new PointerEvent(type, { clientX: x, clientY: y, bubbles: true, pointerId: 1 }),
      );
    }
  };
  // The middle quarter of the picture: source pixels 80,45 → 160×90.
  drag(px + pw * 0.25, py + ph * 0.25, px + pw * 0.75, py + ph * 0.75);
  job = await exportNow();
  ok("a crop drawn on the middle of the picture arrives as the middle of the source",
    !!job.crop && near(job.crop.x, 80, 3) && near(job.crop.y, 45, 3) &&
      near(job.crop.w, 160, 4) && near(job.crop.h, 90, 4),
    JSON.stringify(job.crop));

  // ── Output naming ─────────────────────────────────────────────────────────

  ok("the export never lands on the file it came from",
    job.output.endsWith("veditcheck-edit.mp4") && !job.output.endsWith("/veditcheck.mp4"),
    job.output);
  ok("re-editing an export does not stack suffixes",
    suggestName("clip-edit.mp4") === "clip-edit.mp4", suggestName("clip-edit.mp4"));
  ok("a file with no extension still gets one", suggestName("recording") === "recording-edit.mp4",
    suggestName("recording"));

  // ── Faces (item 19) ───────────────────────────────────────────────────────
  //
  // The detector itself is checked in facecheck and the filter graph in
  // ffmpeg.rs. What is only checkable here is the wire between them: that a
  // click really pulls frames, that the boxes come back in *source* pixels
  // rather than at the extractor's resolution, and that they reach the Job.

  ok("a clean edit sends no blurs at all", (job.blur ?? []).length === 0,
    JSON.stringify(job.blur));

  const facesBtn = (): HTMLButtonElement =>
    Array.from(root().querySelectorAll<HTMLButtonElement>("button")).find((b) =>
      b.title.includes("blur each one"),
    )!;
  const scan = async (): Promise<void> => {
    press("blur each one");
    for (let i = 0; i < 800 && facesBtn().disabled; i++) {
      await new Promise((r) => setTimeout(r, 25));
    }
  };
  const note0 = (): string => root().querySelector(".vedit-note")?.textContent ?? "";

  serveFaces = false;
  await scan();
  ok("a clip with nobody in it says so rather than quietly doing nothing",
    note0().toLowerCase().includes("no faces"), note0());
  ok("and arms nothing", facesBtn().textContent === "Blur faces", facesBtn().textContent ?? "");

  serveFaces = true;
  await scan();
  ok("a face in the frame is found and counted", note0().includes("1 face"), note0());
  ok("and the button says what will happen at export",
    (facesBtn().textContent ?? "").startsWith("Blurring"), facesBtn().textContent ?? "");

  job = await exportNow();
  const blurs = job.blur ?? [];
  ok("the export carries the blurs", blurs.length > 0, String(blurs.length));
  ok("in source pixels, inside the frame",
    blurs.every((b) => b.x >= 0 && b.y >= 0 && b.x + b.w <= 320 && b.y + b.h <= 180),
    JSON.stringify(blurs[0]));
  ok("as whole pixels, because crop and overlay take no fractions",
    blurs.every((b) => Number.isInteger(b.x) && Number.isInteger(b.w)), JSON.stringify(blurs[0]));
  ok("over a real stretch of the source timeline",
    blurs.every((b) => b.from >= 0 && b.to <= 8 && b.to > b.from), JSON.stringify(blurs[0]));
  ok("big enough to be a face and not the whole picture",
    blurs.every((b) => b.w > 20 && b.w < 200), blurs.map((b) => b.w).join(","));

  press("Forget the faces");
  ok("clearing them puts the button back", facesBtn().textContent === "Blur faces",
    facesBtn().textContent ?? "");
  job = await exportNow();
  ok("and the next export carries none", (job.blur ?? []).length === 0, JSON.stringify(job.blur));
  serveFaces = false;

  // ── Progress and failure ──────────────────────────────────────────────────

  // Start one and deliberately leave it running — progress only means anything
  // while there is something to be in the middle of.
  lastJob = null;
  refreshed = 0;
  press("never touched");
  for (let i = 0; i < 60 && !lastJob; i++) await new Promise((r) => setTimeout(r, 16));
  await new Promise((r) => setTimeout(r, 0));

  progressCb?.({ id: 7, fraction: 0.42, seconds: 3, speed: 2.5, fps: 60 });
  const note = (): string => root().querySelector(".vedit-note")?.textContent ?? "";
  ok("progress for this job is reported", note().includes("42%"), note());
  progressCb?.({ id: 99, fraction: 0.9, seconds: 9, speed: 1, fps: 30 });
  ok("progress for somebody else's job is not", note().includes("42%"), note());

  doneCb?.({ id: 7, ok: false, output: "", leftover: "C:/clips/x.mp4.facet-part",
    error: "Invalid argument", copied: false });
  ok("a failure says what went wrong", note().includes("Invalid argument"), note());
  ok("and names the partial rather than pretending it is not there",
    note().includes(".facet-part"), note());
  ok("without claiming the folder changed", refreshed === 0, String(refreshed));

  // A failure ends the job, so the success case needs its own.
  lastJob = null;
  press("never touched");
  for (let i = 0; i < 60 && !lastJob; i++) await new Promise((r) => setTimeout(r, 16));
  await new Promise((r) => setTimeout(r, 0));
  doneCb?.({ id: 7, ok: true, output: "C:/clips/veditcheck-edit.mp4", leftover: "",
    error: "", copied: true });
  ok("a lossless save says so", note().includes("bit-for-bit"), note());
  ok("and the folder is told to reload so the file appears", refreshed === 1, String(refreshed));

  // ── The filmstrip ─────────────────────────────────────────────────────────

  for (let i = 0; i < 100 && root().querySelectorAll(".vedit-strip img").length < 12; i++) {
    await new Promise((r) => setTimeout(r, 20));
  }
  ok("the filmstrip fills in", root().querySelectorAll(".vedit-strip img").length === 12,
    String(root().querySelectorAll(".vedit-strip img").length));

  console.log(`vedit: ${passed} passed${failed ? `, ${failed} FAILED` : ""}`);
}

void run().catch((e: unknown) => {
  console.error(`vedit harness threw: ${String(e)}`);
});
